### ISSUE TITLE
Skip indexing Already Indexed  Pages

### ISSUE THREAD

**Issue by toowxxyz** [harrison-broadbent/gsc-auto-index-script#1]
Hello, Thank you for creating this awesome tool. I would really love it if you could create a feature that could skip already indexed pages, as there are sites with a huge number of pages.

This would really help people who manage multiple sites.

**Comment by harrison-broadbent** [comment]
Hey i'm glad you found this useful! 

I've looked into this more, but I don't think its possible with just the API methods on the Google Search Console API. There's no way that I can see to get a list of all the indexed pages of a site. 

An alternative that I'm considering is introducing threading to the script, which would let 2-3 pages be indexed at a time. So if it currently takes, say, 1 hour to index a 1000 page site, it would cut it down to 20-25. 

Another alternative might be to let you provide a CSV/text file of a list of new pages that you want to index/index first 

Thoughts?

**Comment by toowxxyz** [comment]
I like the idea of uploading page links.

I have another question, does your tool use Google Indexing API?

**Comment by harrison-broadbent** [comment]
@toowxxyz It uses this API — https://developers.google.com/webmaster-tools/v1/api_reference_index — which let's it directly interact with Google Search Console

**Comment by harrison-broadbent** [comment]
I've just pushed that update! see this new part of the README — https://github.com/harrison-broadbent/gsc-auto-index-script#index_from_csv
